test for standard conformance
also one quick fix: complex => cmplx

note that the current code does not compile
Intel compiler:
/tmp/stdlib/build/src/stdlib_experimental_linalg_diag.f90(7): error #6645: The name of the module procedure conflicts with a name in the encompassing scoping unit.   [DIAG_RSP]
      function diag_rsp(v) result(res)
GNU compiler
/tmp/stdlib/src/tests/optval/test_optval.f90:252:15:

  252 |     z = optval(x, [2.0_qp, -2.0_qp])
        |               1
        Error: ‘x’ at (1) is an array and OPTIONAL; IF IT IS MISSING, it
        cannot be the actual argument of an ELEMENTAL procedure unless
        there is a non-optional argument with the same rank (12.4.1.5)
        [-Werror=pedantic]