Fix compilation error for NAG
NAG detects a duplicated name for error_handler which is defined
as module procedure as well as the name of the interface of said
procedure:

    Error: src/stdlib_bitsets.f90, line 2131: ERROR_HANDLER previously declared as a generic procedure name
           detected at ERROR_HANDLER@(